# Intro to PyTorch

In [1]:
import torch
torch.__version__

'2.11.0+cpu'

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Tensors

### Create Tensors

A scalar is a non-dimensional tensor.

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
# Tensor back as python int
scalar.item()

7

In [17]:
# Vector: 1 dimensional tensor and is flexible to what it can represent( like [3, 2, 1] or more numbers too.)
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [18]:
vector.ndim

1

In [19]:
## Shape tells us how many elements are in one dimension
vector.shape

torch.Size([2])

In [26]:
MATRIX = torch.tensor([[7, 8, 9, 10, 11],
                      [9, 10, 11, 12, 13]])

MATRIX

tensor([[ 7,  8,  9, 10, 11],
        [ 9, 10, 11, 12, 13]])

In [27]:
MATRIX.ndim

2

In [28]:
MATRIX.shape

torch.Size([2, 5])

In [29]:
MATRIX[1]

tensor([ 9, 10, 11, 12, 13])

In [32]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Nueral networks are initiated with random tensors and adjust those random numbers during back prop.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

In [15]:
# Random tensor

## Size of (4,5)

random_tensor = torch.randn(3, 4)
random_tensor

tensor([[ 0.2735,  0.9663,  1.1068, -0.8954],
        [-0.1920, -0.9650, -0.3343,  0.2475],
        [-0.5659, -1.0755, -0.3851, -1.4220]])

In [4]:
random_tensor.ndim

2

In [5]:
random_tensor.shape

torch.Size([3, 4])

In [9]:
# Create random tensor with similar shape to a image tensor

random_image_size_tensor = torch.randn(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

## Height, width, color channels

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

This is usually for attention masks.

In [13]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
zero*random_tensor

tensor([[0., 0., 0., -0.],
        [-0., -0., -0., 0.],
        [-0., -0., -0., -0.]])

In [17]:
## Create tensors of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

### Create a range of tensor and tensor-like

In [23]:
# Using tensor.range()
one_to_ten = torch.arange(1,11)
one_to_ten, one_to_ten.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [25]:
steps = torch.arange(start=1, end=100, step=23)
steps

tensor([ 1, 24, 47, 70, 93])

In [27]:
tensors = torch.randn(size=(4, 5))

In [29]:
# Tensor like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
zeros = torch.zeros_like(input=tensors)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

### Tensor Datatypes

> 3 main errors I may run into in the future:
> - Tensors not in right datatype: `tensor.dtype`
> - Tensors not right shape: `tensor.shape`
> - Tensors not on right device: `tesnor.device`



In [32]:
# Float 32 tensor

fl_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, # Datatype of tensor(mainly for detail of a single number stored in memory)
                            device=None, # What device is your tesnor on?
                            requires_grad=False) # Whether or not to track gradients
fl_32_tensor

tensor([3., 6., 9.])

In [33]:
fl_16_tensor = fl_32_tensor.type(torch.float16)

fl_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
fl_16_tensor * fl_32_tensor

tensor([ 9., 36., 81.])

### Manipulating tesnors

- Addition
- Subtration
- Multiplication
- Division
- Matrix Multiplication

In [5]:
# Tensor Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [6]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [7]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [8]:
# built in multiplication torch
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Built in addition
torch.add(tensor, 10)

**Matrix Multiplication**

2 types of multiplication
1. Element wise multiplication
2. Matrix multiplication (Dot Product)

2 rules for matmul
1. **Inner dimensions** must match
- `(3, 2) @ (3, 2)` wont work ( Below code )
- `(2, 3) @ (3, 2)` will work

2. The resulting matrix has a shape of the **outer dimensions**:
- `(2, 3) @ (3, 2)` -> `(2,2)`



In [17]:
torch.matmul(torch.randn(3, 2), torch.randn(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [9]:
# Element wise multiplication

print(tensor, '*', tensor)
print(f'Equals: {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [10]:
torch.matmul(tensor, tensor)

tensor(14)

In [13]:
# Matrix multiplication by hand

1*1 + 2*2 + 3*3

14

In [15]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.47 ms, sys: 968 µs, total: 2.43 ms
Wall time: 8.69 ms


In [16]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 243 µs, sys: 16 µs, total: 259 µs
Wall time: 177 µs


tensor(14)

> **Key tip**: Most common errors in DL: shape errors!

In [3]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [4]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues we can manipulate the shape of our tensors using a **transpose**.

A transpose switches the axes or dimensions of a given tensor.

In [5]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [7]:
tensor_B.T.shape

torch.Size([2, 3])

In [9]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [14]:
x = torch.arange(0, 100, 10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [11]:
# Find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [12]:
# Find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [16]:
# NOTE: torch.mean() function requires a float32 dtype
# Find mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [17]:
# Find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [18]:
# Finding the positional min
## This finds the postion of the tesnor that has the min value -> returns index position of target tensor where the min value occurs
x.argmin()

tensor(0)

In [19]:
# Finding the positional max

x.argmax()

tensor(9)

### Reshaping, stacking, squeezing, and unsqueezing

- Reshape: reshapes an input tensor to a defined shape
- View: Return a view of an input tensor of a certain shape but keep the same memory as a original tensor
- Stacking: combine multiple tensors on top of each other or side by side
- squeeze: remove all `1` dimensions from a tensor
- Unsqueeze: add a `1` dimension to a target tensor
- Permute: return a view of the input w/ dimensions permuted in a certain way.

In [24]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [25]:
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [26]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [36]:
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [29]:
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [34]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [42]:
# Squeeze
squeezed = x_reshaped.squeeze()

squeezed, squeezed.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [43]:
# Unsqueeze
unsqueezed = squeezed.unsqueeze(dim=0)
unsqueezed, unsqueezed.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [49]:
# Permute

x_og = torch.randn(size=(224, 224, 3))

x_permuted = x_og.permute(2, 0, 1)
x_og.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing (selecting data from tensors)

This is similar to numpy


In [2]:
x = torch.arange(1, 10).reshape(1, 3, 3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
# Index on tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
# Index on middle bracket

x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [6]:
# Index on inner bracket

x[0][0][0]

tensor(1)

In [7]:
x[0][1][1]

tensor(5)

In [8]:
# Use the ':' to select all of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [9]:
# values of oth and 1st dim but only 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [10]:
# Values of the 0 dimesnion but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [11]:
# Values of the 0th and 1st dimension  and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3,6,9
print(x[:,:,2])

### Pytorch tensors and Numpy

Numpy is a popular scientific python numerical computing library

Because of this, pytorch has functionality to interact with it.

- Data in Numpy, want in pytorch tensor `torch.from_numpy(ndarray)`
- Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [12]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [13]:
array.dtype

dtype('float64')

In [14]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [15]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [16]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducebility

To reduce randomness in NN and pytorch comes the concept of **random seed**

Random seed "flavors" the randomness.


In [17]:
random_A = torch.rand(3,4)
random_B = torch.rand(3, 4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.1083, 0.7688, 0.8169, 0.2308],
        [0.1685, 0.0271, 0.0806, 0.4553],
        [0.7317, 0.8186, 0.8613, 0.9652]])
tensor([[0.7264, 0.4713, 0.6588, 0.3318],
        [0.9930, 0.4991, 0.7289, 0.3042],
        [0.7460, 0.8248, 0.6641, 0.3558]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [20]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
